import re
f = 'msg/scratch_msgs.js'
s = open(f, encoding='utf-8').read()

start = s.index('Blockly.ScratchMsgs.locales["geng"] =')
# find the matching "};" that closes this block (next "\n};" after start)
end = s.index('\n};', start) + len('\n};')

geng = '''Blockly.ScratchMsgs.locales["geng"] =
{
    "CONTROL_FOREVER": "无限循环（死循环）",
    "CONTROL_REPEAT": "循环 %1 次",
    "CONTROL_IF": "要是 %1 就",
    "CONTROL_ELSE": "不然",
    "CONTROL_STOP": "停",
    "CONTROL_STOP_ALL": "所有脚本",
    "CONTROL_STOP_THIS": "这个脚本",
    "CONTROL_STOP_OTHER": "这个崽崽的其他脚本",
    "CONTROL_WAIT": "等 %1 秒",
    "CONTROL_WAITUNTIL": "等到 %1",
    "CONTROL_REPEATUNTIL": "一直循环直到 %1",
    "CONTROL_WHILE": "只要 %1 就循环",
    "CONTROL_FOREACH": "从 %2 里挨个取 %1",
    "CONTROL_STARTASCLONE": "当被分身出来时",
    "CONTROL_CREATECLONEOF": "分身 %1",
    "CONTROL_CREATECLONEOF_MYSELF": "我自己",
    "CONTROL_DELETETHISCLONE": "删掉这个分身",
    "CONTROL_COUNTER": "计数器",
    "CONTROL_INCRCOUNTER": "计数器+1",
    "CONTROL_CLEARCOUNTER": "计数器清零",
    "CONTROL_ALLATONCE": "所有脚本",
    "CONTROL_SWITCH": "看 %1 是啥",
    "CONTROL_CASE": "要是等于 %1",
    "CONTROL_CASE_FALLTHROUGH": "等于 %1（继续往下）",
    "CONTROL_DEFAULT": "其他情况",
    "CONTROL_BREAK": "break（跳出）",
    "CONTROL_CONTINUE": "continue（接着下一个）",
    "DATA_SETVARIABLETO": "把 %1 设为 %2",
    "DATA_CHANGEVARIABLEBY": "给 %1 加 %2",
    "DATA_SHOWVARIABLE": "把 %1 亮出来",
    "DATA_HIDEVARIABLE": "把 %1 藏起来",
    "DATA_ADDTOLIST": "把 %1 塞进 %2",
    "DATA_DELETEOFLIST": "删掉 %2 的第 %1 个",
    "DATA_DELETEALLOFLIST": "清空 %1",
    "DATA_INSERTATLIST": "在 %3 的第 %2 个前面插 %1",
    "DATA_REPLACEITEMOFLIST": "用 %3 换掉 %2 的第 %1 个",
    "DATA_ITEMOFLIST": "%2 的第 %1 个",
    "DATA_ITEMNUMOFLIST": "%2 里第一个 %1 的序号",
    "DATA_LENGTHOFLIST": "%1 的长度",
    "DATA_LISTCONTAINSITEM": "%1 里有 %2 不？",
    "DATA_SHOWLIST": "把列表 %1 亮出来",
    "DATA_HIDELIST": "把列表 %1 藏起来",
    "DATA_INDEX_ALL": "全部",
    "DATA_INDEX_LAST": "最后一个",
    "DATA_INDEX_RANDOM": "随机",
    "EVENT_WHENFLAGCLICKED": "点 %1 就开跑",
    "EVENT_WHENTHISSPRITECLICKED": "点这个崽崽时",
    "EVENT_WHENSTAGECLICKED": "点舞台时",
    "EVENT_WHENTOUCHINGOBJECT": "碰到 %1 时",
    "EVENT_WHENBROADCASTRECEIVED": "收到 %1 时",
    "EVENT_WHENBACKDROPSWITCHESTO": "背景切成 %1 时",
    "EVENT_WHENGREATERTHAN": "当 %1 > %2",
    "EVENT_WHENGREATERTHAN_TIMER": "计时器",
    "EVENT_WHENGREATERTHAN_LOUDNESS": "响度",
    "EVENT_BROADCAST": "广播 %1",
    "EVENT_BROADCASTANDWAIT": "广播 %1 然后等",
    "EVENT_WHENKEYPRESSED": "按 %1 键时",
    "EVENT_WHENKEYPRESSED_SPACE": "空格",
    "EVENT_WHENKEYPRESSED_LEFT": "←",
    "EVENT_WHENKEYPRESSED_RIGHT": "→",
    "EVENT_WHENKEYPRESSED_DOWN": "↓",
    "EVENT_WHENKEYPRESSED_UP": "↑",
    "EVENT_WHENKEYPRESSED_ANY": "任意键",
    "LOOKS_SAYFORSECS": "说 %1 持续 %2 秒",
    "LOOKS_SAY": "说 %1",
    "LOOKS_HELLO": "你好呀！",
    "LOOKS_THINKFORSECS": "想 %1 持续 %2 秒",
    "LOOKS_THINK": "想 %1",
    "LOOKS_HMM": "嗯……（思考中）",
    "LOOKS_SHOW": "显示",
    "LOOKS_HIDE": "隐藏",
    "LOOKS_HIDEALLSPRITES": "全体隐身（崽崽都藏）",
    "LOOKS_EFFECT_COLOR": "颜色",
    "LOOKS_EFFECT_FISHEYE": "鱼眼",
    "LOOKS_EFFECT_WHIRL": "漩涡",
    "LOOKS_EFFECT_PIXELATE": "像素风",
    "LOOKS_EFFECT_MOSAIC": "马赛克",
    "LOOKS_EFFECT_BRIGHTNESS": "亮度",
    "LOOKS_EFFECT_GHOST": "虚化",
    "LOOKS_CHANGEEFFECTBY": "给 %1 效果加 %2",
    "LOOKS_SETEFFECTTO": "把 %1 效果设为 %2",
    "LOOKS_CLEARGRAPHICEFFECTS": "清空特效",
    "LOOKS_CHANGESIZEBY": "大小变 %1",
    "LOOKS_SETSIZETO": "大小设为 %1",
    "LOOKS_SIZE": "大小",
    "LOOKS_COSTUMES": "造型",
    "LOOKS_CHANGESTRETCHBY": "拉伸%1",
    "LOOKS_SETSTRETCHTO": "拉伸设为%1%",
    "LOOKS_SWITCHCOSTUMETO": "切换造型到 %1",
    "LOOKS_NEXTCOSTUME": "下一个造型",
    "LOOKS_SWITCHBACKDROPTO": "切换背景到 %1",
    "LOOKS_GOTOFRONTBACK": "移到最 %1 层",
    "LOOKS_GOTOFRONTBACK_FRONT": "前",
    "LOOKS_GOTOFRONTBACK_BACK": "后",
    "LOOKS_GOFORWARDBACKWARDLAYERS": "%1 %2 层",
    "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "往前",
    "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "往后",
    "LOOKS_BACKDROPNUMBERNAME": "背景 %1",
    "LOOKS_COSTUMENUMBERNAME": "造型 %1",
    "LOOKS_NUMBERNAME_NUMBER": "编号",
    "LOOKS_NUMBERNAME_NAME": "名字",
    "LOOKS_SWITCHBACKDROPTOANDWAIT": "切换背景到 %1 并等",
    "LOOKS_NEXTBACKDROP_BLOCK": "下一个背景",
    "LOOKS_NEXTBACKDROP": "下一个背景",
    "LOOKS_PREVIOUSBACKDROP": "上一个背景",
    "LOOKS_RANDOMBACKDROP": "随机背景",
    "MOTION_MOVESTEPS": "走 %1 步",
    "MOTION_TURNLEFT": "向左转 %1 %2 度",
    "MOTION_TURNRIGHT": "向右转 %1 %2 度",
    "MOTION_POINTINDIRECTION": "朝向 %1",
    "MOTION_POINTTOWARDS": "朝向 %1",
    "MOTION_POINTTOWARDS_XY": "面朝 x: %1 y: %2",
    "MOTION_POINTTOWARDS_XYFROM": "面朝 x: %1 y: %2 从 x: %3 y: %4",
    "MOTION_POINTTOWARDS_POINTER": "鼠标",
    "MOTION_POINTTOWARDS_RANDOM": "随机方向",
    "MOTION_GOTO": "移到 %1",
    "MOTION_GOTO_POINTER": "鼠标",
    "MOTION_GOTO_RANDOM": "随机位置",
    "MOTION_GOTOXY": "移到 x: %1 y: %2",
    "MOTION_GLIDESECSTOXY": "在 %1 秒内滑到 x: %2 y: %3",
    "MOTION_GLIDETO": "在 %1 秒内滑到 %2",
    "MOTION_GLIDETO_POINTER": "鼠标",
    "MOTION_GLIDETO_RANDOM": "随机位置",
    "MOTION_CHANGEXBY": "x 坐标加 %1",
    "MOTION_SETX": "x 坐标设为 %1",
    "MOTION_CHANGEYBY": "y 坐标加 %1",
    "MOTION_SETY": "y 坐标设为 %1",
    "MOTION_IFONEDGEBOUNCE": "碰到边就弹回",
    "MOTION_SETROTATIONSTYLE": "旋转方式设为 %1",
    "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "左右翻转",
    "MOTION_SETROTATIONSTYLE_DONTROTATE": "不旋转",
    "MOTION_SETROTATIONSTYLE_ALLAROUND": "任意旋转",
    "MOTION_XPOSITION": "x 坐标",
    "MOTION_YPOSITION": "y 坐标",
    "MOTION_DIRECTION": "方向",
    "MOTION_SCROLLRIGHT": "向右滚动 %1",
    "MOTION_SCROLLUP": "向上滚动 %1",
    "MOTION_ALIGNSCENE": "对齐场景到 %1",
    "MOTION_ALIGNSCENE_BOTTOMLEFT": "左下",
    "MOTION_ALIGNSCENE_BOTTOMRIGHT": "右下",
    "MOTION_ALIGNSCENE_MIDDLE": "中间",
    "MOTION_ALIGNSCENE_TOPLEFT": "左上",
    "MOTION_ALIGNSCENE_TOPRIGHT": "右上",
    "MOTION_XSCROLL": "x 滚动位置",
    "MOTION_YSCROLL": "y 滚动位置",
    "MOTION_STAGE_SELECTED": "已选舞台：动不了",
    "OPERATORS_ADD": "%1 + %2",
    "OPERATORS_SUBTRACT": "%1 - %2",
    "OPERATORS_MULTIPLY": "%1 * %2",
    "OPERATORS_DIVIDE": "%1 / %2",
    "OPERATORS_RANDOM": "在 %1 和 %2 之间随机抽一个数",
    "OPERATORS_GT": "%1 > %2",
    "OPERATORS_LT": "%1 < %2",
    "OPERATORS_EQUALS": "%1 = %2",
    "OPERATORS_AND": "%1 且 %2",
    "OPERATORS_AND_SEPARATOR": "且",
    "OPERATORS_OR": "%1 或 %2",
    "OPERATORS_OR_SEPARATOR": "或",
    "OPERATORS_NOT": "%1 不成立",
    "OPERATORS_JOIN": "拼接 %1 和 %2",
    "OPERATORS_JOIN_LABEL": "拼接",
    "OPERATORS_JOIN_APPLE": "苹果",
    "OPERATORS_JOIN_BANANA": "香蕉",
    "OPERATORS_LETTEROF": "%2 的第 %1 个字符",
    "OPERATORS_LETTEROF_APPLE": "果",
    "OPERATORS_LENGTH": "%1 的字符数",
    "OPERATORS_CONTAINS": "%1 里有 %2 不？",
    "OPERATORS_MOD": "%1 除以 %2 的余数",
    "OPERATORS_MOD_SEPARATOR": "取余",
    "OPERATORS_MIN": "最小",
    "OPERATORS_MAX": "最大",
    "OPERATORS_CLAMP": "把 %1 限制在 %2 到 %3",
    "OPERATORS_PI": "π",
    "OPERATORS_NEWLINE": "换行",
    "OPERATORS_LETTERSOF": "%3 的第 %1 到 %2 个字符",
    "OPERATORS_INDEXOF": "%1 里 %2 的位置",
    "OPERATORS_REPLACE": "用 %3 替换 %2 里的 %1",
    "OPERATORS_REPLACE_HELLO_WORLD": "你好，世界！",
    "OPERATORS_REPLACE_WORLD": "世界",
    "OPERATORS_REPLACE_FELLOW_SCRATCHERS": "各位创作者",
    "OPERATORS_REPEAT": "%1 重复 %2 次",
    "OPERATORS_CHANGECASE": "把 %1 变成 %2",
    "OPERATORS_LOWERCASE": "小写",
    "OPERATORS_UPPERCASE": "大写",
    "OPERATORS_TRIM": "去掉 %1 两头空格",
    "OPERATORS_ROUND": "四舍五入 %1",
    "OPERATORS_MATHOP": "%1 %2",
    "OPERATORS_MATHOP_ABS": "绝对值",
    "OPERATORS_MATHOP_FLOOR": "向下取整",
    "OPERATORS_MATHOP_CEILING": "向上取整",
    "OPERATORS_MATHOP_SQRT": "平方根",
    "OPERATORS_MATHOP_SIN": "sin",
    "OPERATORS_MATHOP_COS": "cos",
    "OPERATORS_MATHOP_TAN": "tan",
    "OPERATORS_MATHOP_ASIN": "asin",
    "OPERATORS_MATHOP_ACOS": "acos",
    "OPERATORS_MATHOP_ATAN": "atan",
    "OPERATORS_MATHOP_LN": "ln",
    "OPERATORS_MATHOP_LOG": "log",
    "OPERATORS_MATHOP_EEXP": "e ^",
    "OPERATORS_MATHOP_10EXP": "10 ^",
    "PROCEDURES_DEFINITION": "定义 %1",
    "PROCEDURES_RETURN": "返回 %1",
    "PROCEDURES_TO_REPORTER": "改成报值积木",
    "PROCEDURES_TO_STATEMENT": "改成堆叠积木",
    "PROCEDURES_DOCS": "怎么用返回",
    "SENSING_TOUCHINGOBJECT": "碰到 %1 了？",
    "SENSING_TOUCHINGOBJECT_POINTER": "鼠标",
    "SENSING_TOUCHINGOBJECT_EDGE": "舞台边缘",
    "SENSING_TOUCHINGCOLOR": "碰到颜色 %1 了？",
    "SENSING_COLORISTOUCHINGCOLOR": "颜色 %1 碰到 %2 了？",
    "SENSING_DISTANCETO": "到 %1 的距离",
    "SENSING_DISTANCETO_POINTER": "鼠标",
    "SENSING_ASKANDWAIT": "问 %1 然后等",
    "SENSING_ASK_TEXT": "你叫啥名？",
    "SENSING_ANSWER": "回答",
    "SENSING_KEYPRESSED": "按了 %1 键？",
    "SENSING_MOUSEDOWN": "鼠标按下了？",
    "SENSING_MOUSEX": "鼠标的 x 坐标",
    "SENSING_MOUSEY": "鼠标的 y 坐标",
    "SENSING_SETDRAGMODE": "拖拽模式设为 %1",
    "SENSING_SETDRAGMODE_DRAGGABLE": "可拖",
    "SENSING_SETDRAGMODE_NOTDRAGGABLE": "不可拖",
    "SENSING_LOUDNESS": "响度",
    "SENSING_LOUD": "有声吗？",
    "SENSING_TIMER": "计时器",
    "SENSING_RESETTIMER": "计时器清零",
    "SENSING_OF": "%2 的 %1",
    "SENSING_OF_XPOSITION": "x 坐标",
    "SENSING_OF_YPOSITION": "y 坐标",
    "SENSING_OF_DIRECTION": "方向",
    "SENSING_OF_COSTUMENUMBER": "造型编号",
    "SENSING_OF_COSTUMENAME": "造型名字",
    "SENSING_OF_SIZE": "大小",
    "SENSING_OF_VOLUME": "音量",
    "SENSING_OF_BACKDROPNUMBER": "背景编号",
    "SENSING_OF_BACKDROPNAME": "背景名字",
    "SENSING_OF_STAGE": "舞台",
    "SENSING_CURRENT": "现在的 %1",
    "SENSING_CURRENT_YEAR": "年",
    "SENSING_CURRENT_MONTH": "月",
    "SENSING_CURRENT_DATE": "日",
    "SENSING_CURRENT_DAYOFWEEK": "星期",
    "SENSING_CURRENT_HOUR": "时",
    "SENSING_CURRENT_MINUTE": "分",
    "SENSING_CURRENT_SECOND": "秒",
    "SENSING_DAYSSINCE2000": "从 2000 年到现在的天数",
    "SENSING_ONLINE": "在线吗？",
    "SENSING_USERNAME": "用户名",
    "SENSING_USERID": "用户 id",
    "SENSING_STAGEWIDTH": "舞台宽度",
    "SENSING_STAGEHEIGHT": "舞台高度",
    "SOUND_PLAY": "播放声音 %1",
    "SOUND_PLAYUNTILDONE": "播放声音 %1 直到放完",
    "SOUND_STOPALLSOUNDS": "停止所有声音",
    "SOUND_SETEFFECTO": "把 %1 音效设为 %2",
    "SOUND_CHANGEEFFECTBY": "把 %1 音效加 %2",
    "SOUND_CLEAREFFECTS": "清空音效",
    "SOUND_EFFECTS_PITCH": "音调",
    "SOUND_EFFECTS_PAN": "左右声道",
    "SOUND_CHANGEVOLUMEBY": "音量加 %1",
    "SOUND_SETVOLUMETO": "音量设为 %1%",
    "SOUND_VOLUME": "音量",
    "SOUND_RECORD": "录制…",
    "CATEGORY_MOTION": "运动",
    "CATEGORY_LOOKS": "外观",
    "CATEGORY_SOUND": "声音",
    "CATEGORY_EVENTS": "事件",
    "CATEGORY_CONTROL": "控制",
    "CATEGORY_SENSING": "侦测",
    "CATEGORY_OPERATORS": "运算",
    "CATEGORY_VARIABLES": "变量",
    "CATEGORY_MYBLOCKS": "我的积木",
    "CATEGORY_STRINGS": "字符串",
    "CATEGORY_ASSETS": "素材",
    "ASSETS_MANAGE": "管理素材",
    "ASSETS_LOAD": "加载素材 %1 为 %2",
    "ASSETS_KIND_COSTUME": "造型",
    "ASSETS_KIND_SOUND": "声音",
    "ASSETS_UNLOAD": "卸载素材 %1",
    "ASSETS_UNLOADALL": "卸载全部素材",
    "ASSETS_GET": "%2 的%1",
    "ASSETS_PROPERTY_TEXT": "文本",
    "ASSETS_PROPERTY_DATAURI": "数据URI",
    "ASSETS_PROPERTY_BASE64": "Base64",
    "ASSETS_PROPERTY_URL": "链接",
    "ASSETS_PROPERTY_SIZE": "大小",
    "ASSETS_PROPERTY_FORMAT": "格式",
    "ASSETS_PROPERTY_FOLDER": "文件夹",
    "ASSETS_BYTE": "%2 的第 %1 字节",
    "ASSETS_CHECK": "%1 %2 不？",
    "ASSETS_STATE_EXISTS": "存在",
    "ASSETS_STATE_LOADED": "已加载",
    "ASSETS_SET": "把素材 %1 设为 %2 作 %3",
    "ASSETS_DELETE": "删除素材 %1",
    "ASSETS_ALLNAMES": "所有素材名字",
    "ASSETS_INFOLDER": "%1 文件夹里的素材",
    "DUPLICATE": "复制",
    "DELETE": "删除",
    "ADD_COMMENT": "加注释",
    "REMOVE_COMMENT": "删注释",
    "DELETE_BLOCK": "删除",
    "DELETE_X_BLOCKS": "删除 %1 个积木",
    "DELETE_ALL_BLOCKS": "要删掉全部 %1 个积木不？",
    "CLEAN_UP": "整理积木",
    "HELP": "帮助",
    "UNDO": "撤销",
    "REDO": "重做",
    "EDIT_PROCEDURE": "编辑",
    "SHOW_PROCEDURE_DEFINITION": "看它的定义",
    "WORKSPACE_COMMENT_DEFAULT_TEXT": "说点啥……",
    "COLOUR_HUE_LABEL": "色相",
    "COLOUR_SATURATION_LABEL": "饱和度",
    "COLOUR_BRIGHTNESS_LABEL": "亮度",
    "CHANGE_VALUE_TITLE": "改个变量：",
    "RENAME_VARIABLE": "改个变量名",
    "RENAME_VARIABLE_TITLE": "把所有「%1」变量名改成：",
    "RENAME_VARIABLE_MODAL_TITLE": "改变量名",
    "NEW_VARIABLE": "新建一个变量",
    "NEW_VARIABLE_TITLE": "新变量名：",
    "VARIABLE_MODAL_TITLE": "新变量",
    "VARIABLE_ALREADY_EXISTS": "已经有个叫「%1」的变量了。",
    "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "已经有个叫「%1」的变量，类型是「%2」。",
    "DELETE_VARIABLE_CONFIRMATION": "要删掉 %1 处的「%2」变量不？",
    "CANNOT_DELETE_VARIABLE_PROCEDURE": "删不了变量「%1」，因为函数「%2」的定义用到了它",
    "DELETE_VARIABLE": "删除变量「%1」",
    "NEW_PROCEDURE": "做个新积木",
    "PROCEDURE_ALREADY_EXISTS": "已经有个叫「%1」的程序了。",
    "PROCEDURE_DEFAULT_NAME": "积木名",
    "PROCEDURE_USED": "删积木定义前，先在用到它的地方把它删掉。",
    "NEW_LIST": "新建一个列表",
    "NEW_LIST_TITLE": "新列表名：",
    "LIST_MODAL_TITLE": "新列表",
    "LIST_ALREADY_EXISTS": "叫「%1」的列表已经存在了。",
    "RENAME_LIST_TITLE": "把所有「%1」列表改名：",
    "RENAME_LIST_MODAL_TITLE": "改列表名",
    "DEFAULT_LIST_ITEM": "东西",
    "DELETE_LIST": "删除「%1」列表",
    "RENAME_LIST": "改列表名",
    "NEW_BROADCAST_MESSAGE": "新消息",
    "NEW_BROADCAST_MESSAGE_TITLE": "新消息名：",
    "BROADCAST_MODAL_TITLE": "新消息",
    "DEFAULT_BROADCAST_MESSAGE_NAME": "消息1",
    "UNSUPPORT_TW_1": "下面这些积木 TurboWarp 不支持",
    "UNSUPPORT_TW_2": "真心劝你别用",
    "UNSUPPORT_TW_3": "它只是为了和 MistWarp 兼容才留着。"
};
'''

s = s[:start] + geng + s[end:]
open(f, 'w', encoding='utf-8').write(s)
print('geng blocks fully rewritten')
